import { lib, game, ui, get, ai, _status } from "../../../../noname.js";
//武将文本信息，技能翻译文本信息，标签翻译文本信息
const translates = {
   

xinfan_xingsunluban: "星孙鲁班",
xinfan_fugu: '跗骨',
xinfan_fugu_info: '锁定技,每轮游戏开始时，你选择一名其他角色。其摸牌/于弃牌阶段弃置牌时，你摸/弃置等量牌。',
xinfan_gongfu: '共赴',
xinfan_gongfu_info: '一张基本牌或普通锦囊指定唯一目标时，若你为使用者或目标角色，你可以为此牌额外指定一个目标,且不能为使用者。',
   
xinfan_xingzhonghui: "星钟会",
xinfan_quanji: '权计',
xinfan_quanji_info: '当你受到伤害/造成伤害时，你可以摸一张牌/防止此伤害并摸一张牌。当你摸牌后，你可以将一张牌置于一名角色武将牌上称“权”，其手牌上限加x（x为其武将牌上"权"数量）。',
xinfan_zili: '自立',
xinfan_zili_info: `觉醒技，当“权”数量不小于你的体力上限后，你回复一点体力并摸两张牌，然后获得技能${get.poptip("xinfan_paiyi")}。`,
xinfan_paiyi: '排异',
xinfan_paiyi_backup: '排异',
xinfan_paiyi_info: '出牌阶段限一次，你可以弃置一张“权”，令一名角色摸两张牌并对其造成一点伤害。武将牌上有“权”的角色不因此技能受到伤害时，你可对其造成一点伤害，然后你令其获得其武将牌上一张"权"。',

xinfan_xingfeiyi: "星费祎",
xinfan_huyuan: '互援',
xinfan_huyuan_info: '当一名角色受到伤害后，你可与其各摸一张牌，若受伤角色不为你，你交给其一张手牌。当你失去最后手牌后，所有角色依次选择是否交给你一张手牌，然后你与交给你牌的角色，各摸一张牌。',
xinfan_zhige: '止戈',
xinfan_zhige_info: '结束阶段开始时，你可以选择一名其他角色，你令其回复1点体力或摸2张牌，然后你执行另一项。直到你的下个回合开始前，你们相互间每回合内首次造成的伤害减1。',

xinfan_xingtongyuan: "星童渊",
xinfan_bailian: '百炼',
xinfan_bailian_info: '游戏开始时，你获得技能“静水”，“流转”，“奔流”，并获得对应名称标记。准备阶段开始时，你令一名角色获得一枚任意标记，若其未获得对应技能，其获得之（每个技能的x为其对应标记数量）。',
xinfan_jingshui: '静水',
xinfan_jingshui_info: '锁定技，每回合x次，当你成为其他角色使用牌的目标时，摸一张牌（每个技能的x为其对应标记数量）。',
xinfan_liuzhuan: '流转',
xinfan_liuzhuan_info: '每回合x次，你可以将任意基本牌/锦囊牌，视为任意基本牌/锦囊牌使用或打出（每个技能的x为其对应标记数量）。',
xinfan_benliu: '奔流',
xinfan_benliu_info: '每局游戏限x次，出牌阶段你可以选择一名其他角色，本回合内你对其使用牌无距离次数限制（每个技能的x为其对应标记数量）。',
xinfan_cba: '静水',
xinfan_cba_info: '锁定技，每回合x次，当你成为其他角色使用牌的目标时，摸一张牌（每个技能的x为其对应标记数量）。',
xinfan_cad: '流转',
xinfan_cad_info: '每回合x次，你可以将任意基本牌/锦囊牌，视为任意基本牌/锦囊牌使用或打出（每个技能的x为其对应标记数量）。',
xinfan_cbd: '奔流',
xinfan_cbd_info: '每局游戏限x次，出牌阶段你可以选择一名其他角色，本回合内你对其使用牌无距离次数限制（每个技能的x为其对应标记数量）。',

xinfan_xingzhugeguo: "星诸葛果",
xinfan_chenyuan_tag: "尘缘",
xinfan_chenyuan: "塵緣",
xinfan_chenyuan_info: "锁定技，你的初始手牌标记为 “尘缘”牌。当你进 入濒死状态时，若你手牌中有“尘缘”牌，你回复体力至1点。",
xinfan_chaotuo: "超脱",
xinfan_chaotuo_info: `觉醒技，当你失去最后的 “尘缘”牌后，你弃置区域内所有牌并将体力回复至上限，废除你的装备区和判定区，失去出牌阶段以外所有阶段，获得技能${get.poptip("xinfan_piaoyi")}`,
xinfan_piaoyi: "飘逸",
xinfan_piaoyi_info: "锁定技，你须将获得的牌以任意顺序置于牌堆顶或牌堆底。当你需要使用牌时，你可以观看牌堆顶2x张牌，无距离限制且无来源的使用其中一张牌(x为游戏轮数)。",
   
xinfan_xingjiangwei: "星姜维",
xinfan_tiaoxin: "挑衅",
xinfan_tiaoxin_info: "其他角色的出牌阶段开始时， 你可以令其选择一项:1.对你使用一张无距离限制的[杀]，且本回合内使用牌不能指定你与其以外的角色为目标。2.令你弃置其一张牌，且本回合内使用牌不能指定你为目标。",
xinfan_hemou: "合谋",
xinfan_hemou_info: " 限定技，出牌阶段，你可以选择一名其他角色， 你与其依次摸三张牌后依次受到三点火焰伤害，本回合结束时，你与其依次恢复3点体力。",
xinfan_zhiji: "志继",
xinfan_zhiji_info: `觉醒技，当你失去所有手牌或进入濒死状态后，你将手牌/体力补充至体力上限并获得技能${get.poptip("xinfan_yibo")}`,
xinfan_yibo: "衣钵",
xinfan_yibo_info: "准备阶段开始时，你观看牌堆顶3张牌并以任意顺序放回牌堆顶。当你没有手牌时，你不能成为[杀]的目标。",

xinfan_xingzhangchunhua: "星张春华",
xinfan_jueqin: "绝情",
xinfan_jueqin_info: "锁定技，每回合一次,防止你造成或受到的伤害。免伤角色本回合获得“绝情”标记。持有“绝情”标记的角色，其受到的伤害改为体力流失并令你摸一张牌。",
xinfan_zhinian: "执念",
xinfan_zhinian_info: "每回合每种类别限一张，当你的牌进入弃牌堆时，你可以获得之，本回合内你使用此牌无次数限制。",                 

xinfan_xingsimayi: "星司马懿",
xinfan_yingshi: "鹰视",
xinfan_yingshi_info: "一名角色的回合结束阶段开始时，若你于本回合内没有成为过其他角色使用牌的目标，则你可以恢复一点体力或摸两张牌。一名角色的准备阶段开始时，你可以将任意张手牌置于武将牌上称“鹰视”牌，或将任意张“鹰视”牌收回手牌。",
xinfan_chengbing: "称病",
xinfan_chengbing_info: "其他角色的出牌阶段开始时，你可以令其观看你的手牌。若其中没有伤害类牌，则其本回合内使用[杀]或[决斗]不能指定你为目标。当你对其他角色造成伤害后，此技能本轮内失效。",

xinfan_xingcaocao: "星曹操",
xinfan_zhiyuan: "志远",
xinfan_zhiyuan_info: "锁定技，当你的手牌数量大于手牌上限时，你将超出数量的手牌置于武将牌上称“志”。你的武将牌上每有1张“志”，你的手牌上限加1。每名角色的回合结束阶段你将1张“志”收回手牌。",
xinfan_haina: "海纳",
xinfan_haina_info: "锁定技，当你受到伤害后，你获得对你造成伤害的牌并收回1张“志”。当你不是从牌堆中获得牌时，你展示获得牌中的一张，随机展示并获得牌堆中一张同类别的牌。",
 
xinfan_xinghuangyueying: "星黄月英",
xinfan_lingdong: "灵动",
xinfan_lingdong_info: "当你需要使用一张基本牌或普通锦囊牌时，你可以声明此牌的【牌名】【花色】【点数】并视为使用之。若如此做，你须弃置一张同名称的牌，否则此技能本回合失效。",
xinfan_lingqiao: "灵巧",
xinfan_lingqiao_info: "当你使用牌后，你可以记录此牌的【花色】【点数】【牌名】【类别】中未记录的一项。若你记录至少两项，则你可以随机展示牌堆里一张满足条件的牌并交给一名角色并清除记录。若没有满足条件的牌，则改为清除一项记录。",
 
xinfan_xingcaoren: "星曹仁",
xinfan_dingjun: "定军",
xinfan_dingjun_info: "每回合限一次；当你的体力值或手牌数量发生变动后，你可以将手牌数量调整至当前体力值。当你以此法摸牌/弃牌时，你可以令一名其他角色摸/弃置等量牌。",
xinfan_jiyuan: "急援",
xinfan_jiyuan_info: "限定技，当一名角色进入濒死状态后，你可以弃置区域内所有牌令其将体力值回复至一点，然后本局游戏内“定军”每回合内使用次数加一。若你以此法弃置牌的数量不小于其体力上限，你与其额外回复一点体力。",

xinfan_xingzhaoyun: "星赵云",
xinfan_qiangshi_tag: "势",
xinfan_qiangshi: "枪势",
xinfan_qiangshi_info: "锁定技，游戏开始时，你将牌堆顶2x张牌至于武将牌上称“势”。当“势”数量减少后，你从牌堆顶补充等量张(x为你的体力上限)。",
xinfan_youlong: "游龙",
xinfan_youlong_info: "群势力技， 当你使用或打出牌后，你获得一枚“游”标记。你可以弃置两枚‘游”标记使用一张“势”牌，然后你本回合内下一张牌无次数限制，若此时为回合外，则改为获得一枚“游龙”标记。",
xinfan_zhenjun: "镇军",
xinfan_zhenjun_info: "蜀势力技，当你使用或打出手牌后,你可以弃置一张“势”。你的准备阶段或结束阶段开始时，你可以将任意张“势”牌交给一名角色(至多不超过你的体力上限)。",

xinfan_xingweiyan: "星魏延",
xinfan_kuanggu: '狂骨',
xinfan_kuanggu_info: '锁定技，你对与你计算距离为1的角色造成伤害后，回复一点体力。每个你造成过伤害的回合结束后，你摸两张牌。',
xinfan_yexi: '夜袭',
xinfan_yexi_info: '群势力技，你与当前回合的其他角色计算距离视为一。每回合限一次，其他角色的出牌阶段开始/结束时，你可以视为对其使用一张[杀]。',
xinfan_zhukou: '逐寇',
xinfan_zhukou_info: '蜀势力技，出牌阶段内，你可以失去一点体力并弃置其他角色一张牌。若你与该角色计算距离大于一/等于一，你本回合内与其他角色计算距离减一/获得弃置的牌。',
   
xinfan_xingyuji: "星于吉",
xinfan_guanshi: '观世',
xinfan_guanshi_info: `锁定技，游戏开始时，你令所有其他角色获得技能${get.poptip("xinfan_miaofa")}，然后你直到本轮结束前离开游戏。`,
xinfan_rushi: '入世',
xinfan_rushi_info: `觉醒技，当你进入再次进入游戏时，若“虚”数量大于/不大于“实”，你获得技能${get.poptip("xinfan_huanmeng")}/${get.poptip("xinfan_fushi")}，然后所有其他角色失去技能${get.poptip("xinfan_miaofa")}。'`,
xinfan_miaofa: '妙法',
xinfan_miaofa_info: '每回合一次，你可以将一张牌，视为非装备牌使用且不能指定其他角色为目标。回合结束时，若本回合内有人使用了虚拟转化牌，你获得“虚”标记，否则你获得“实”标记。',
xinfan_huanmeng: '幻梦',
xinfan_huanmeng_info: '每回合限3次，你可以视为使用一张非装备牌且不能指定其他角色为目标。其他角色使用的虚拟转化牌对你无效。',
xinfan_fushi: '浮世',
xinfan_fushi_info: '锁定技,每回合3次,其他角色使用非装备牌后,你摸一张牌。当你成为其他角色使用牌的目标时，你可以弃置一张同名牌，令之无效。',
  
xinfan_xingsimazhao: "星司马昭",
xinfan_daigong: '怠攻',
xinfan_daigong_info: '锁定技，游戏开始时，你获得三枚“怠”，当你受到伤害时，移去所有”怠”标记防止之。每回合你首次造成的伤害增加1-“怠”数量点。',
xinfan_qiantun: '谦吞',
xinfan_qiantun_info: '每回合一次，当你使用的牌结算完成后，你可以重铸2张牌，每回合内你以此法首次弃置基本牌/锦囊牌/装备牌后，你可以视为使用一张无次数限制的[杀]/摸1张牌/弃置其他角色1张牌。',
  
xinfan_xingzhoucang: "星周仓",
xinfan_zhongyong: '忠勇',
xinfan_zhongyong_info: '锁定技，当你失去最后的护甲时，你减少一点体力上限，令一名角色摸两张牌，然后你获得两点护甲。',
xinfan_xiezhan: '协战',
xinfan_xiezhan_info: '当一张[杀]指定目标后，你可以弃置一张牌令使用者选择一项：1.此牌不计入次数限制。2.此牌不可被响应。背水.你失去一点护甲。',
 
xinfan_xingwolongfengchu: "星卧龙凤雏",
xinfan_longpo: '龙魄',
xinfan_longpo_info: '卧龙技，游戏开始时/出牌阶段内，你获得/令一名角色获得一枚“魄”标记和1点护甲。持有“魄”标记的角色成为其他角色使用牌的目标时，可以弃置此标记令之无效，并回复1点体力，重复获得此标记时，改为回复1点体力。',
xinfan_fengming: '凤鸣',
xinfan_fengming_info: '凤雏技，出牌阶段限一次，你可以减少一点体力对一名角色依次造成共计自身体力值点火焰伤害',
xinfan_huizhuan: '回转',
xinfan_huizhuan_info: '游戏开始时，你自选形态。出牌阶段限一次，你可以弃置x张牌，转换形态，并将体力值调整至已损失体力值。当你以此法失去体力值时，你摸等量牌。（x为本局游戏内此技能使用次数）',

xinfan_xingxushi: "星徐氏",
xinfan_bugua: '卜卦',
xinfan_bugua_info: '一名角色的准备阶段开始时，你可以展示一张手牌并卜算X，若其中有与你展示牌同类别或同名牌，你获得一枚“卜”标记（X为“卜”标记数量加1且至多不超过5）然后你摸一张牌。',
xinfan_bixiong: '避凶',
xinfan_bixiong_info: '每回合限一次，当你成为其他角色使用牌的目标时，使用者以外的其他角色可以取消之，并令你发动一次“卜卦”。',

xinfan_xingxiahoushi: "星夏侯氏",
xinfan_degui: '得归',
xinfan_degui_area: '得归',
xinfan_degui_info: '当你获得牌后，你可以任意调整“库”与手牌，。“库”最大数量为4张且可以视为手牌使用或打出，出牌阶段内你可以弃置两张牌令库最大数量加1至多不超过8。',
xinfan_qiaoshi: '樵拾',
xinfan_qiaoshi_info: '一名角色的出牌阶段开始时，你观看牌堆顶3张牌，并获得一种类别的所有牌，若当前回合角色不为你，其可以视为对你使用一张无距离限制的[杀]。',
xinfan_yanyv: '燕语',
xinfan_yanyv_info: '锁定技，当你成为其他角色使用伤害牌的目标时其可以改为观看你的手牌并获得你一张牌',

xinfan_xingsunjian: "星孙坚",
xinfan_yinghun: '英魂',
xinfan_yinghun_info: '锁定技,每名角色的回合结束阶段，你令一名角色摸x张牌并弃置y张牌(x为你本回合内使用的手牌数量，y为本回合内你成为其他角色使用牌目标的次数)。',
 
xinfan_xingwangyi: "星王异",
xinfan_zhenlie: '贞烈',
xinfan_zhenlie_info: '当你成为其他角色使用牌的目标时/受到其他角色造成的伤害时，你可以流失一点体力防止之，然后你弃置来源一张牌。',
xinfan_zhenlie_add_info: '你可以流失一点体力防止此伤害，然后你弃置伤害来源一张牌。',
xinfan_miji: '秘技',
xinfan_miji_info: '每名角色的回合结束阶段，若你本回合内使用过牌或减少过体力值。你摸已损失体力值的牌，然后你可以交给一名其他角色至多等量张牌，然后你声明一张基本牌或普通锦囊牌的牌名，其可以将此牌视为你声明的牌名使用。且以此法使用的牌名对你无效。',
                
xinfan_xingcaiwenji: "星蔡文姬",
xinfan_boyue: "博阅",
xinfan_boyue_info: "锁定技，当你使用或打出的牌结算完成后,若你未记录此牌名,你记录之。当你于自己的回合内首次记录牌名时，你摸一张牌。",
xinfan_moshi: "默识",
xinfan_moshi_info: "每回合每种类别限一次,当你需要使用或打出牌时,你可以移除“博阅”记录的一张牌名，获得并使用一张同名牌（无论它在哪）。",

xinfan_xingzhouxuan: "星周宣",
xinfan_wuwei: '无为',
xinfan_wuwei_info: '每回合一次，你可以视为使用一张基本牌或普通锦囊牌。然后，当前回合角色须选择一项：1.本回合内不能使用打出或弃置手牌。2.弃置一张同类别牌。',
xinfan_wuwei_discard: '请弃置一张同类别的手牌，否则，本回合内不能使用打出或弃置手牌。',
xinfan_qingmeng: '清梦',
xinfan_qingmeng_info: '每轮一次，一名角色回合结束后，你可以令一名角色执行一个不能使用或打出手牌的回合。',
};

export default translates;