import { lib, game, ui, get, ai, _status } from "../../../../noname.js";
//武将文本信息，技能翻译文本信息，标签翻译文本信息
const translates = {
          
xinfan_shenqihuang: "神启荒",
xinfan_qishenqi: '神启',
xinfan_qishenqi_info: '锁定技，每轮游戏开始时，所有角色移除其以此法记录的牌名，获得一张对应的牌。然后你为所有角色分配一张牌名令其记录之。',
xinfan_qimingding: '命定',
xinfan_qimingding_info: '当一名角色使用或打出其“神启”记录的牌名结算后，你可以令其受到1点无来源伤害。然后你将此牌置于武将牌上称“命定”牌。',
xinfan_qixinggui: '星轨',
xinfan_qixinggui_info: '你可以将“命定”牌视为手牌使用或打出。当你使用牌指定目标后，你可以依次对其使用“命定”牌中的同名牌',

xinfan_qianji: "千姬",
xinfan_chaoge: "潮歌",
xinfan_chaoge_info: "锁定技,当你使用或打出牌或受到伤害后，你获得一枚“潮歌”标记，当你持有的此标记数量大于4后，你清除此标记，回复1点体力并摸3张牌。",
xinfan_ningshuang: "凝霜",
xinfan_ningshuang_info: `出牌阶段限一次，你可以弃置1张牌，令一名其他角色获得“霜”标记。持有此标记的角色，回合结束后，需要弃置2张手牌，若其因此失去最后的手牌或没有手牌，其${get.poptip("xinfan_yongdong")}。`,
xinfan_yongdong: '永冻',
xinfan_yongdong_info: '下个回合开始时，跳过本回合并摸2张牌。',

xinfan_xinyouquanshen: "心友犬神",
xinfan_xinyou: "心友",
xinfan_xinyou_info: "每轮游戏开始时,若场上“心友”角色数量小于2,你可以将一名其他角色标记为“心友”角色。你使用伤害牌不能指定“心友”角色为目标。",
xinfan_shouhu: "守护",
xinfan_shouhu_info: "每回合每名角色限一次,当你或“心友”角色成为伤害牌的目标时,若来源不是“心友”角色,你令其选择一项:1.取消之。2.此牌结算完成后,你视为对其使用一张[杀]。",
xinfan_youli: "友力",
xinfan_youli_info: "锁定技,当你使用[杀]指定目标后,场上每有一名“心友”角色,此[杀]额外结算一次。",

xinfan_lingluyuqian: "铃鹿御前",
xinfan_lulanggui: "浪归",
xinfan_lulanggui_info: `出牌阶段内，你可以弃置至多两张牌并选择一名其他角色，然后你选择一项：1.你获得等量点护甲其执行一个${get.poptip("xinfan_lulanggui_suo")}回合。2.你对其造成等量点伤害。`,
xinfan_luyili: "义理",
xinfan_luyili_info: "你持有护甲期间，受到的伤害不超过1点。",
xinfan_lulanggui_suo: "义争",
xinfan_lulanggui_suo_info: "此回合内使用牌无距离次数限制且仅能指定持有技能“浪归”的角色为目标，本回合结束后翻面。",

xinfan_fuguqingji: "缚骨清姬",
xinfan_qingchanxin: '缠心',
xinfan_qingchanxin_info: `锁定技，你使用【杀】指定目标后其获得一层${get.poptip("xinfan_du")}。`,
xinfan_qingshigu: '蚀骨',
xinfan_qingshigu_info: '锁定技，当一名角色流失体力后，你回复1点体力，然后若你的体力上限小于10，则你增加1点体力上限，否则你摸2张牌。',
xinfan_qingjianggu: '降蛊',
xinfan_qingjianggu_info: `限定技，你可以选择一名其他角色，本局游戏内，你与其回合开始时，其获得一层${get.poptip("xinfan_du")}。`,
xinfan_du: '毒',
xinfan_du_info: '回合开始时，移去一枚并流失1点体力。',

xinfan_longjue: "龙珏",
xinfan_longcuijian: '摧坚',
xinfan_longcuijian_info: '锁定技，你造成伤害时，若目标没有"摧坚"标记,改为令其获得之。持有“摧坚”标记的角色受到的伤害增加其体力上限点并移除此标记。',
xinfan_longlongxi: '龙息',
xinfan_longlongxi_info: '每轮一次，当你受到伤害时/出牌阶段内，你可以，防止此伤害并获得一个额外回合/获得一个额外回合。',

xinfan_jinnaluo: "紧那罗",
xinfan_jinzouxu: "奏序",
xinfan_jinzouxu_info: `出牌阶段限一次，你可以展示牌堆顶4张牌，并获得其中一张牌。若此牌颜色为♥/♦/♠/♣，你可以执行"${get.poptip("xinfan_jinzouxu_gong")}"/"${get.poptip("xinfan_jinzouxu_shang")}"/"${get.poptip("xinfan_jinzouxu_jiao")}"/"${get.poptip("xinfan_jinzouxu_hui")}"。`,
xinfan_jinyayin: "雅音",
xinfan_jinyayin_info: `回合结束时，你可以获得一个额外回合，并失去技能“奏序”，获得技能“${get.poptip("xinfan_jinzoulv")}”。`,
xinfan_jinzoulv: '奏律',
xinfan_jinzoulv_info: `出牌阶段限一次，你可以依次执行"宫""商""角""徽"中本局游戏内你执行过的一项。`,
xinfan_jinzouxu_gong: "宫",
xinfan_jinzouxu_gong_info: '对一名角色造成1点伤害。',
xinfan_jinzouxu_shang: "商",
xinfan_jinzouxu_shang_info: '令一名角色摸2张牌。',
xinfan_jinzouxu_jiao: "角",
xinfan_jinzouxu_jiao_info: '弃置一名角色区域内1张牌。',
xinfan_jinzouxu_hui: "徽",
xinfan_jinzouxu_hui_info: '令一名角色回复1点体力。',

xinfan_guiqie: "鬼切",
xinfan_guijianshan: '剑闪',
xinfan_guijianshan_info: '回合结束阶段，你可以视为使用一张无距离限制的[杀]。',
xinfan_guiguiren: '鬼刃',
xinfan_guiguiren_info: '锁定技，你使用的杀结算完成后，若目标已受伤，其流失一点体力。',

xinfan_guitongwan: "鬼童丸",
xinfan_guiyueyin: '月隐',
xinfan_guiyueyin_info: '锁定技，游戏开始时，你获得1点护甲，并进入不可选中状态，直到你的下个回合开始前。',
xinfan_guihaisuo: '骸锁',
xinfan_guihaisuo_info: '锁定技，当你造成/受到伤害后，受伤角色/来源，获得一枚“锁”标记。',
xinfan_guikuanglie: '狂猎',
xinfan_guikuanglie_info: '锁定技，当场上“锁”标记数量不小于你的体力上限后，发动技能“月隐”清空场上“锁”标记，分配等量点无来源伤害。',

xinfan_xunsenxiaolunan: "寻森小鹿男",
xinfan_lusenxin: '森心',
xinfan_lusenxin_info: '游戏开始时，你获得一枚“森”标记。结束阶段，你可以令一名未持有“森”标记的其他角色获得“森”标记。持有此标记的其他角色造成伤害后，获得一枚“侵”标记。',
xinfan_lusenqi: '森契',
xinfan_lusenqi_info: '锁定技，准备阶段开始时，你回复场上“森”标记数量点体力并摸等量张牌。然后你弃置持有"侵"标记角色的一张牌,并弃置其持有的一枚"侵"标记,若其没有牌,则改为造成一点伤害。重复此操作，直至场上没有"侵"标记。',

xinfan_dishitian: "帝释天",
xinfan_dizhanfang: '绽放',
xinfan_dizhanfang_info: '出牌阶段限一次，你可以令一名角色流失一点体力或回复一点体力。',
xinfan_dilianhua: '莲华',
xinfan_dilianhua_info: '出牌阶段限一次，若场上，没有/有，“莲”标记，你可以令一名角色获得“莲”标记/转移“莲”标记。当你进入濒死状态时，你可以移去场上“莲”标记，发动技能“绽放”。',
xinfan_dijinlian: '金莲',
xinfan_dijinlian_info: '每回合一次，当持有“莲”标记的角色，使用牌或打出牌或造成伤害或回复体力时，你可以取消之。',

xinfan_yuanlaiguang: "源赖光",
xinfan_guangxueqi: '血契',
xinfan_guangxueqi_info: '锁定技，准备阶段开始时，你清除场上“血契”标记，令一名角色获得“血契”标记。持有“血契”标记的角色，每回合首次受到的伤害减1。',
xinfan_guangbuwu: '布武',
xinfan_guangbuwu_info: '出牌阶段限一次，你可以选择一名其他角色，你弃置其装备区和手牌区各一张牌，然后对其造成一点伤害。',
xinfan_guangzhuijiao: '追剿',
xinfan_guangzhuijiao_info: '每轮一次，当其他角色受到伤害或体力值减少后，若其已损失体力值大于其体力值，你可以对其造成1点伤害。',

xinfan_cimutongzi: "茨木童子",
xinfan_cihaoyi: '豪意',
xinfan_cihaoyi_info: '出牌阶段限一次，你可以对一名其他角色造成x加1点伤害（x为你“怒”标记数量）。',
xinfan_ciqiannu: '迁怒',
xinfan_ciqiannu_info: '锁定技，当你造成伤害结算完成后，若目标，存活/阵亡，你获得一枚“怒”标记（至多持有3枚）/移除所有“怒”标记并分配等量点无来源伤害。',

xinfan_tianrenjianxinguiqie: "天韧剑心鬼切",
xinfan_qietianren: '天韧',
xinfan_qietianren_info: '当你成为其他角色使用牌的目标时，你可以进行一次判定，若二者类别相同，则取消之。',
xinfan_qieduane: '断恶',
xinfan_qieduane_info: '准备阶段开始时，你重新标记一名其他角色为“危”角色。“危”角色防具失效，你与其的回合结束后，你视为对其使用一张[杀]。',

xinfan_chulingshanfeng: "初翎山风",
xinfan_shanchuling: '初翎',
xinfan_shanchuling_info: '出牌阶段限1次,你可以分配1点护甲或伤害。',
xinfan_shanxunyu: '迅羽',
xinfan_shanxunyu_info: '锁定技，每名角色的回合结束后/你每回合首次受到伤害后,你获得1枚“迅”标记。当你持有的“迅”标记数量不小于3时,你获得一个额外的回合并移除“迅”标记。',

xinfan_chanbingxuenv: "蝉冰雪女",
xinfan_xueyongdong: '永冻',
xinfan_xueyongdong_info: '出牌阶段限1次,你可以获得一点护甲，然后选择一名其他角色，你与其下个回合改为摸2张牌并跳过。',
xinfan_xueshuanghan: '霜寒',
xinfan_xueshuanghan_info: '锁定技，每3个场上角色的回合结束后，你可以弃置场上一张牌或造成一点伤害。',
xinfan_xuechungao: '春告',
xinfan_xuechungao_info: '限定技，出牌阶段内，你可以选择一名已阵亡的角色，其复活，并将体力值和手牌数量补充至体力上限。',

xinfan_huojinshen: "祸津神",
xinfan_huohuozhou: '祸咒',
xinfan_huohuozhou_info: '锁定技，出牌阶段结束后,你重新将一名其他角色标记为“祸咒”角色。你每回合内首次受到伤害后，其受到一点无来源伤害。然后你受到一点无来源伤害。',
xinfan_huodaogao: '祷言',
xinfan_huodaogao_info: '每回合每名角色限一次，当一名角色受到伤害后，你可以令其获得一点护甲。',

xinfan_shenduobaqidashe: "神堕八岐大蛇",
xinfan_sheqiying: '岐影',
xinfan_sheqiying_info: '锁定技，游戏开始时或你的回合结束后，你将手牌和体力值存入“虚空”并使用“巫女之怨”替换武将牌。',
xinfan_shezhongyan: '终焉',
xinfan_shezhongyan_info: '登场技，你从“虚空”中取回你的体力值和手牌，然后你弃置所有“终焉”标记，分配等量点伤害。',

xinfan_wunvzhiyuan: "巫女之怨",
xinfan_shebeiming: '悲鸣',
xinfan_shebeiming_info: '登场技，摸3张牌。',
xinfan_shejishen: '祭身',
xinfan_shejishen_info: '锁定技，准备阶段开始时或当你阵亡时，你使用八岐大蛇替换武将牌，“八岐大蛇”获得你体力值点“终焉”标记，然后获得你的体力值和手牌。',

xinfan_huangkulou: "荒骷髅",
xinfan_kuhaixi: '骸袭',
xinfan_kuhaixi_info: '出牌阶段限一次，你可以流失一点体力，视为使用一张牌无距离次数限制且不可响应的任意[杀]。',
xinfan_kuliehun: '烈魂',
xinfan_kuliehun_info: '你每回合首次于受伤/阵亡状态下，造成的伤害加1/2。',
xinfan_kuzhanqi: '战旗',
xinfan_kuzhanqi_info: `限定技，当一名角色进入濒死状态时,你可以令其将体力值回复至1点,并获得2点护甲。然后，本回合结束后你执行一个${get.poptip("xinfan_shixi")}回合`,    

xinfan_xueyuqian: "雪御前",
xinfan_xueqianxue: '千雪',
xinfan_xueqianxue_info: '锁定技，你的[杀]视为不可响应的冰[杀]。',
xinfan_xuexuezhan: '雪绽',
xinfan_xuexuezhan_info: '锁定技，当你使用的[杀]结算完成后,目标角色获得两枚“雪”标记。当一名角色持有的“雪”标记数量不小于其体力值后，其移除其持有的“雪”标记，并流失一点体力。',
xinfan_xuelongli: '龙璃',
xinfan_xuelongli_info: '游戏开始时或你的回合开始时，若你没有护甲，你获得两点护甲,否则你摸两张牌。',    
 
xinfan_xuzuozhinan: "须佐之男",    
xinfan_xushenyou: '神佑',
xinfan_xushenyou_info: '每轮游戏开始时，你庇护任意名其他角色，你与被庇护的角色的准备阶段开始时，其可以令你对一名其他角色造成一点伤害并令你获得一点护甲，然后庇护角色，本回合内造成伤害时，防止之。',
xinfan_xushenfa: '神罚',
xinfan_xushenfa_info: '锁定技，你的[杀]或造成的伤害均视为雷属性。当你造成伤害不小于目标体力值时，若其武将牌不为“天羽羽斩”,你改为令其使用“天羽羽斩”代替武将牌。',


xinfan_tianyuyuzhan: "天羽羽斩", 
xinfan_xuxingjian: '刑监',
xinfan_xuxingjian_info: `锁定技，你始终跳过自己的回合，当你阵亡后，若来源未持有“${get.poptip("xinfan_xushenfa")}”,你使用原武将牌替换此武将牌。登场技，你进行一次，胜负判断。锁定技，你进行胜负判断期间视为死亡。` ,        

xinfan_pingjiangmen: "平将门",    
xinfan_pingluanzhen: '乱阵',
xinfan_pingluanzhen_info: '出牌阶段内,你可以与一名本回合内未收到过你伤害的角色进行【决斗】。',
xinfan_pingbudu: '布都',
xinfan_pingbudu_info: `游戏开始时或回合结束时，你选择一个架势，${get.poptip("xinfan_pingbudu_lie")}/${get.poptip("xinfan_pingbudu_nuan")}`,
xinfan_pingjiaoyang: '骄阳',
xinfan_pingjiaoyang_info: `每轮一次，当你累计造成或受到的伤害次数不小于你的体力上限后，你执行一个${get.poptip("xinfan_shixi")}回合并重新计数”。`,
xinfan_pingbudu_lie: '烈日',
xinfan_pingbudu_lie_info: '每回合首次造成的伤害加1。',
xinfan_pingbudu_nuan: '暖阳',
xinfan_pingbudu_nuan_info: '每回合首次受到伤害后，你与任意名角色回复1点体力。',


xinfan_ji: "季",    
xinfan_jisiji: '四季',
xinfan_jisiji_info: '转换技，每轮游戏开始时，春：你令任意名角色回复1点体力，然后你获得1点护甲。夏：你令任意名角色弃置2张牌。秋：你令任意名角色摸2张牌，然后你摸1张牌。冬：你令任意名角色失去1点体力。',
xinfan_jiliuzhuan: '流转',
xinfan_jiliuzhuan_info: '锁定技，每局游戏限x次，当你进入濒死状态时，你回复所有体力，发动一次“四季”（x为“四季”轮回次数加1）。',
xinfan_chun: '春',
xinfan_xia: '夏',
xinfan_qiu: '秋',
xinfan_dong: '冬',

xinfan_chanxinyunwaijing: "禅心云外镜",    
xinfan_chanjiekong: '皆空',
xinfan_chanjiekong_info: '出牌阶段内，你可以令一名角色将体力值流失至1点，然后其获得已损失体力值点护甲，你的下两个非“净明”回合结束后，其回复体力至已损失体力值，期间此技能失效，其手牌上限增加其护甲值点。',
xinfan_chanjingming: '净明',
xinfan_chanjingming_info: '准备阶段开始时，你可以跳过本回合，然后选择一名判定区内有/没有牌的角色，令其弃置判定区内的牌/执行一个额外回合。',

xinfan_liuguangzhuiyueshen: "流光追月神",    
xinfan_zhuiliuguang: '流光',
xinfan_zhuiliuguang_info: '每轮游戏开始时，你弃置所有“流光”标记，回复等量点体力，然后获得3枚“流光”标记。',
xinfan_zhuiqiwu: '绮舞',
xinfan_zhuiqiwu_info: '一名角色回合开始时，你可以弃置一枚“流光”标记，令一名角色摸2张牌或弃置场上2张牌。',
xinfan_zhuininghui: '凝辉',
xinfan_zhuininghui_info: '出牌阶段限一次,你可以弃置两张牌获得2枚“流光”标记。',

xinfan_kongxiangmianlingqi: "空相面灵气",
xinfan_miankongxiang: '空相',
xinfan_miankongxiang_info: '转换技，当你不因此技能，使用牌指定目标或成为牌的目标时，改为，阳：来源视为对自己使用此牌。阴：目标视为对自己使用此牌。',
xinfan_mianweiwo: '唯我',
xinfan_mianweiwo_info: '锁定技，当你对自己使用牌后，摸一张牌。当你受到伤害时，若来源不为你，则取消之。',
   
xinfan_xiaolanghuangchuanzhizhu: "晓浪荒川之主",
xinfan_chuanxiaolang: '晓浪',
xinfan_chuanxiaolang_info: `出牌阶段限一次，你可以${get.poptip("xinfan_chuanxiaolang_start")}一名其他角色并对其造成1点伤害。`,
xinfan_chuanchuannu: '川怒',
xinfan_chuanchuannu_info: '锁定技，其他角色造成伤害后，你获得等量枚“川”标记，当你“川”标记数量大于3后，你弃置所有“川”标记,获得一个额外回合。',    
xinfan_chuanyili: '屹立',
xinfan_chuanyili_info: '锁定技，当你阵亡后，你分配体力上限点体力回复。此后，每轮游戏结束后，你可以对任意名角色造成1点伤害。',  
xinfan_chuanxiaolang_start: '孤立',
xinfan_chuanxiaolang_start_info: '锁定技，当你回复体力时，若来源不为你，则取消之。',    

xinfan_linghaijinyuji: "聆海金鱼姬",    
xinfan_yulinghai: '聆海',
xinfan_yulinghai_info: '出牌阶段限一次，若你有/没有“聆”标记，你可以弃置一枚“聆”标记，摸两张牌/弃置两张牌，获得一枚“聆”标记。当你失去最后的“聆”标记后，你获得一个额外回合。',
xinfan_yulingbo: '凌波',
xinfan_yulingbo_info: '一名角色回合结束后，你可以弃置一枚“聆”标记，令其选择一项:1.造成1点伤害。2.回复1点体力。',

xinfan_yanling: "言灵", 
xinfan_yanyuzui: '语罪',
xinfan_yanyuzui_info: '每轮游戏开始时,你可以记录或删除至多3项"语罪"记录。当你使用或打出牌后,若此牌名你未记录,则记录之。',
xinfan_yankuangmo: '诳默',
xinfan_yankuangmo_info: '当其他角色使用牌时，若“语罪”记录了此牌名，你可以移去此牌名，令之无效。',
xinfan_yanzhenyan: '真言',
xinfan_yanzhenyan_info: '每回合限一次，你可以获得并使用一张“语罪“中未记录的牌，并记录此牌名。',

xinfan_kongquemingwang: "孔雀明王", 
xinfan_quemili: '迷离',
xinfan_quemili_info: '当其他角色使用杀时，你可以获得一枚“翎”标记并进行一次判定，若二者类别相同则取消之。自己的回合结束阶段你获得一枚“翎”标记。',
xinfan_quekaiping: '开屏',
xinfan_quekaiping_info: `锁定技，当你的“翎”标记数量不小于5后，你回复等量点体力并摸等量张牌，然后你失去技能“迷离”获得技能${get.poptip("xinfan_quequewu")}。`,
xinfan_quequewu: '雀舞',
xinfan_quequewu_info: '锁定技，你使用的[杀]无距离次数限制且无视防具。每当你使用[杀]后，你弃置一枚“翎”标记，当你失去最后的“翎”标记后，你失去此技能并获得技能“迷离”。自己的回合结束阶段你弃置所有“翎”标记并摸等量张牌',

xinfan_yixienamei: "伊邪娜美", 
xinfan_meifenzheng: '纷争',
xinfan_meifenzheng_info: '锁定技，准备阶段开始时，所有其他角色依次对你以外的一名角色造成1点伤害。',
xinfan_meichenlun: '沉沦',
xinfan_meichenlun_info: '出牌阶段内，你可以选择一名其他角色，其跳过下一个回合。直到其下回合结束前，你不可再指定其为此技能目标。',

xinfan_longyechaji: "泷夜叉姬", 
xinfan_chalongyue: '胧月',
xinfan_chalongyue_info: '出牌阶段限一次,你可以弃置至多2张牌,执行以下效果：不小于1，对一名角色造成1点伤害。不小于2，回复1点体力。',
xinfan_chayueheng: '月恒',
xinfan_chayueheng_info: '游戏开始时或出牌阶段限一次，你可以切换招式。侵略：造成伤害时，获得对方一张牌。飞流：造成的伤害加一。风疾：造成或受到的伤害视为体力流失。不动：造成或受到伤害时，摸一张牌。',
xinfan_chayueheng_qin: '侵略',
xinfan_chayueheng_liu: '飞流',
xinfan_chayueheng_feng: '风疾',
xinfan_chayueheng_dong: '不动',

xinfan_yuedu: "月读",
xinfan_yuexvdan: '虚诞',
xinfan_yuexvdan_info: '转换技，当你使用牌或成为牌的目标时，若此牌，阳：有，阴：没有，对应的实体牌则无效。',
xinfan_yuetianji: '天极',
xinfan_yuetianji_info: '转换技，每回合两次，你可以，阳：视为，阴：获得并，使用一张基本牌或普通锦囊牌。',
xinfan_yuehuoxing: '惑星',
xinfan_yuehuoxing_info: '转换技，每回合一次，当你使用牌后，你可以转换，阳：“虚诞”，阴：“天极”的阴阳形态。',
xinfan_yuehuang: "哈~谎言被揭穿了~",

xinfan_benzhensanweihu: "本真三尾狐", 
xinfan_huhuying: '狐影',
xinfan_huhuying_info: '当一名其他角色受到伤害后,你可以失去点1点护甲视为对其使用一张[杀]。',
xinfan_hushexin: '摄心',
xinfan_hushexin_info: '锁定技,当你于回合内/外,造成伤害时,回复1点体力/获得目标一张牌。',
xinfan_hulinghe: '灵合',
xinfan_hulinghe_info: '锁定技,回合结束后,若你有/没有护甲，你获得1点护甲/2点护甲。',

xinfan_daoheshenyuzhuanjing: "稻荷神御馔津", 
xinfan_daofengmou: '封魔',
xinfan_daofengmou_info: '当你使用[杀]指定目标后，可以进行一次判定,若结果为♥/♦/♠/♣,则目标，下次回复体力/摸牌/造成伤害/使用牌时,取消之(重复获得时,叠加次数)。',
xinfan_daoriyao: '日耀',
xinfan_daoriyao_info: '每名其他角色回合结束时，你可以视为对其使用一张[杀]。',
xinfan_daoyueying: '月影',
xinfan_daoyueying_info: '出牌阶段限一次,你可以令一名角色摸2张牌,并无距离次数限制的使用一张牌。',

xinfan_xunxiangxing: "寻香行", 
xinfan_xunxiangyin: '香引',
xinfan_xunxiangyin_info: '每名角色回合结束时，你可以获得一张本回合内进入弃牌堆的牌。',
xinfan_xunmingxiang: '明香',
xinfan_xunmingxiang_info: '锁定技，场上角色受到伤害/回合结束后，其/所有角色，获得一枚”香“标记。当一名角色持有的”香“标记数量不小于3时，你移去其持有的”香“标记，令其回复或流失1点体力。',

xinfan_yinfanhuiyeji: "因幡辉夜姬", 
xinfan_fanyuanman: '愿满',
xinfan_fanyuanman_info: '一名角色回合开始时,你可以令其从前x项中,选择一项:1.摸两张。2.回复1点体力。3造成1点伤害。4.增加1点体力上限。然后你获得一枚“愿”标记。(x为“愿”标记数量+1)。',
xinfan_fanyueying: '月盈',
xinfan_fanyueying_info: '一名角色造成伤害或恢复体力时，你可以弃置一枚“愿”标记，本次数值加1。',

xinfan_zhuiyueshen: "追月神",    
xinfan_zhuiqinghui: '清辉',
xinfan_zhuiqinghui_info: '每回合一次，当你成为其他角色使用牌的目标时，你可以无效之,并发动一次“邀月”。',
xinfan_zhuiyaoyue: '邀月',
xinfan_zhuiyaoyue_info: '转换技,一名角色回合结束后，阳：你摸2张牌。阴：令一名角色摸1张牌。',

xinfan_huiyeji: "辉夜姬", 
xinfan_huiyuejing: '月境',
xinfan_huiyuejing_info: '锁定技，场上角色回合开始时或受到伤害时你获得1枚“辉”标记。',
xinfan_huihuiye: '辉夜',
xinfan_huihuiye_info: '当一名角色准备阶段开始时或受到伤害后，你可以弃置2枚/3枚“辉”标记，令其摸2张牌/自选一张牌获得。',

xinfan_geye: "葛叶", 
xinfan_gehuanhua_info: `锁定技，其他角色回合开始时，你 ${get.poptip("xinfan_gehuaxing")} 为其。`,
xinfan_geheshou: '合守',
xinfan_geheshou_info: '出牌阶段限一次，你可以一名角色下次受到的伤害（重复获得叠加次数），然后，你可以发动其一个非特殊技能的，主动技或阶段开始时触发的被动技。',
xinfan_gehuaxing: '化形',
xinfan_gehuaxing_info: '本回合内获得其技能，且可以观看并使用其手牌。',
xinfan_gehuanhua: '幻化',
xinfan_gehuanhua_tag: '幻化',
xinfan_gehuanhua_clear: '幻化',

xinfan_fengyangjun: "封阳君", 
xinfan_fengfengyang: '封阳',
xinfan_fengfengyang_info: '出牌阶段开始时，你可以跳过本回合并视为使用一张无距离限制的[杀]。',
xinfan_fengwangyue: '望月',
xinfan_fengwangyue_info: '转换技，当你使用[杀]指定目标时，阳:目标弃置两张牌,你获得1点护甲。阴:此[杀]伤害加1,你摸1张牌。',
xinfan_fengxunbu: '巡捕',
xinfan_fengxunbu_info: '每轮一次，其他角色回合结束后，你可以执行一个只能对其使用牌的回合。',

xinfan_mengshanbaizangzhu: "梦山白藏主", 
xinfan_baizhanmeng: '斩梦',
xinfan_baizhanmeng_info: '出牌阶段限一次，你可以弃置一张牌视为使用一张无视距离和防具的[杀]。当你受到其他角色造成的伤害后，你可以其对发动"斩梦"。',
xinfan_baiyushou: '御守',
xinfan_baiyushou_info: '锁定技，每轮游戏开始时，你摸2张牌并令一名角色回复1点体力，若其未受伤则改为获得1点护甲。',
xinfan_baishanshi: '山誓',
xinfan_baishanshi_info: '每回合每名角色限一次，其他角色受到伤害时，若来源不为你，你可以代替之。',

xinfan_guiwangjiutuntongzi: "鬼王酒吞童子",
xinfan_tunfentian: '焚天',
xinfan_tunfentian_info: '出牌阶段限一次,你可以视为使用一张无距离次数限制的火[杀]且可额外指定x个目标(x为你已损失体力值)。',
xinfan_tunguiwang: '鬼王',
xinfan_tunguiwang_info: '锁定技,每回合1次，造成伤害加1或受到伤害减1。',
xinfan_tunnuyan: '怒焱',
xinfan_tunnuyan_info: `一名角色准备阶段开始时,你可以令其流失1点体力并弃置判定区内所有牌。若其不为你,其直到下个回合开始前获得${get.poptip("xinfan_tunguiwang")}`,

xinfan_yuyuanbore: "御怨般若",
xinfan_boyuyuan: '御怨',
xinfan_boyuyuan_info: '当你不因此技能,使用的基本牌或普通锦囊牌结算完成后,你可以视为使用一张同名牌。',
xinfan_bohenfan: '恨返',
xinfan_bohenfan_info: '锁定技,其他角色造成伤害后,你获得1枚“仇恨”标记,当你持有此标记数量不小于3后,你弃置所有此标记和判定区内所有牌,本轮内所有伤害均视为体力流失,本轮结束时,你获得一个额外回合。',

xinfan_bujianyue: "不见岳",
xinfan_bushanxing: '山行',
xinfan_bushanxing_info: '出牌阶段限一次，你可以令一名其他角色受到1点伤害或恢复1点体力。',
xinfan_buguyue: '古岳',
xinfan_buguyue_info: '每回合一次，其他角色造成伤害时，你可以令本次伤害加1或减1。',

xinfan_geliuduo: "歌留多", 
xinfan_gewuguang: '五光',
xinfan_gewuguang_info: `锁定技,当你使用牌时,你记录此牌花色,若此牌有目标且不为你，其也记录此牌花色。当一名角色以此法记录四种花色后,其移除其记录的所有花色并流失4点体力。`,
xinfan_gehuayi: '花忆',
xinfan_gehuayi_info: `出牌阶段内,每种花色限一次,你可以移除一名角色"四光"记录的一种花色,并从牌堆中随机获得一张对应花色的牌。`,
xinfan_geqingduan: '青短',
xinfan_geqingduan_info: '当你成为其他角色使用牌的目标时，你可以移除”四光“记录中的对应花色,取消之。',

xinfan_xiuluoguitongwan: "修罗鬼童丸",
xinfan_guiluowang: '罗网',
xinfan_guiluowang_info: '当你不因此技能造成或受到伤害后，你可以对非来源或非受伤角色，依次造成1点伤害。',
xinfan_guishouyi: '狩衣',
xinfan_guishouyi_info: '每轮限x次，当你受到伤害或流失体力或失去体力上限时，你可以改为摸x张牌（x为你本局击杀角色数量加1）。',
xinfan_xiuguikuanglie: '狂猎',
xinfan_xiuguikuanglie_info: '出牌阶段限x次，你可以摸x张牌，然后直到你下次造成或受到伤害前，你的所有手牌均视为无距离次数限制的【杀】（x为你本局击杀角色数量）。',

xinfan_beimihu: "卑弥呼", 
xinfan_beirihui: '日辉',
xinfan_beirihui_info: `每轮游戏开始时，你可以选择一名上轮未选择过的角色，其调离至本轮结束，并于本轮结束时，执行一个${get.poptip("xinfan_shixi")}回合。`,
xinfan_beirilun: '日轮',
xinfan_beirilun_info: '你的摸牌阶段的摸牌数量和出牌阶段的出【杀】次数加x（x为游戏轮数且至多为7）。',
xinfan_shixi: '时隙',
xinfan_shixi_info: '只有摸牌和出牌阶段的回合。',

xinfan_shiyaolongyechaji: "时耀泷夜叉姬",
xinfan_chashiyao: '时耀',
xinfan_chashiyao_info: '准备阶段开始时，你，日耀：增加1点体力上限。月升：回复1点体力。',
xinfan_chalunzhuan: '轮转',
xinfan_chalunzhuan_info: `一名角色回合结束后，你可以执行一个${get.poptip("xinfan_shixi")}回合。`,
xinfan_chashiji: '时寂',
xinfan_chashiji_info: `你的${get.poptip("xinfan_shixi")}回合内，所有其他角色不能使用或打出牌，所有伤害效果延迟至下一名角色回合开始时，合并结算。`,

xinfan_yaohu: "妖狐", 
xinfan_hujuqi: '聚气',
xinfan_hujuqi_info: '你不以其他角色为目标的牌结算完成后，你观看牌堆顶x张牌并获得其中一张（x为3+此技能本回合内使用次数）。',
xinfan_hukuanglan: '狂岚',
xinfan_hukuanglan_info: '当你使用【杀】指定目标后，你可以展示牌堆顶1张牌，若为【杀】，则你可以对其使用此牌，然后你可以重复此操作。',

};

export default translates;
